apiVersion: v1
kind: Service
metadata:
  name: ${NAME}-mysql
  labels:
    app: ${NAME}
spec:
  ports:
    - port: 3306
  selector:
    app: ${NAME}
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-${NAME}-pv-claim
  labels:
    app: ${NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${NAME}-mysql
  labels:
    app: ${NAME}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${NAME}
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-${NAME}-pass
              key: password-${NAME}.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-${NAME}-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-${NAME}-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-${NAME}-pv-claim
