apiVersion: v1
kind: Service
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
spec:
  ports:
    - port: 80
  selector:
    app: ${NAME}
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-${NAME}-pv-claim
  labels:
    app: ${NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${NAME}
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.7.3-apache
        name: wordpress
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: WORDPRESS_DB_HOST
          value: ${NAME}-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-${NAME}-pass
              key: password-${NAME}.txt
        ports:
        - containerPort: 80
          name: ${NAME}
        volumeMounts:
        - name: wordpress-${NAME}-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-${NAME}-persistent-storage
        persistentVolumeClaim:
          claimName: wp-${NAME}-pv-claim
